# group_vars/ec2_servers.yml
app_name: "Gateway"
app_user: "www-data"
app_group: "www-data"
app_directory: "/var/www/your-app"
app_executable: "KejaHunT_Gateway"  # Your .NET executable name
app_port: "5000"
dotnet_version: "8.0"
aspnet_environment: "Production"

# Environment variables for your app
app_env_vars:
 ReverseProxy__Clusters__fileHandlerService__Destinations__files__Address: "https://localhost:7115/"
 ReverseProxy__Clusters__propertyService__Destinations__properties__Address: "http://3.87.211.55:5000/"
 ReverseProxy__Clusters__accessService__Destinations__access__Address: "https://localhost:7159/"